webtalk_init -webtalk_dir C:/Users/husain/Documents/GitHub/CIFAR10_CNN/week01/week01.sim/sim_1/behav/xsim/xsim.dir/matrix_mult_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov  6 00:31:27 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "203015195_203016366_210761572_921" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "71fed8d7-d6a9-4d41-a03b-cf99e02b5f48" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "52d4d64787024793bdd264d793c5af76" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "34" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2296 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "130 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6572_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2500047269 -regid "203015195_203016366_210761572_921" -xml C:/Users/husain/Documents/GitHub/CIFAR10_CNN/week01/week01.sim/sim_1/behav/xsim/xsim.dir/matrix_mult_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/husain/Documents/GitHub/CIFAR10_CNN/week01/week01.sim/sim_1/behav/xsim/xsim.dir/matrix_mult_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/husain/Documents/GitHub/CIFAR10_CNN/week01/week01.sim/sim_1/behav/xsim/xsim.dir/matrix_mult_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
